### ISSUE TITLE
meaning of 608 in "Prepare_data.sh" execution

### ISSUE THREAD

**Issue by ingbeeedd** [jkjung-avt/yolov4_crowdhuman#18]
When I download data, do specify 608 to build a directory name to make it easier to use later, regardless of the size of the data? So, the data doesn't change according to the arugument, does it? It automatically resize when I train the model anyway? Thank you

**Comment by jkjung-avt** [comment]
When preparing yolo (darknet) annotations, I filter out objects that are too small for the model to learn.  Reference: https://github.com/jkjung-avt/yolov4_crowdhuman/issues/12#issuecomment-757396925

The filtering would be dependent upon input dimension.  That's why I chose to create different data directories for models with different input dimensions.

**Comment by ingbeeedd** [comment]
Then, if you give 416x256 as input, what would be the change?

**Comment by jkjung-avt** [comment]
> Then, if you give 416x256 as input, what would be the change?

It should be pretty straightforward.

1. `$ ./prepare_data.sh 416x256`
2. `$ ./prepare_training.sh 416x256`
3. Create "cfg/yolov4-crowdhuman-416x256.cfg".  Remember to re-calculate the "anchors" in the cfg.
4. Train the model using the new cfg.
