### ISSUE TITLE
Regarding Prepare_data.sh

### ISSUE THREAD

**Issue by Venketaramana** [jkjung-avt/yolov4_crowdhuman#20]
Hi @jkjung-avt,

I understand that the gen_texts module resizes the dataset and converts the odgt annotations to YOLO annotations. Can you advise me on how to modify the code to resize and prepare a custom dataset which is already in YOLO.txts format?

**Comment by jkjung-avt** [comment]
Please refer to [How to train (to detect your custom objects)](https://github.com/AlexeyAB/darknet) of the original DarkNet README.  The yolo annotations should contain 1 txt for each jpg image in the dataset.  And the txt file consists of lines of texts as defined below:

> <object-class> <x_center> <y_center> <width> <height>
> 
> Where:
> 
> <object-class> - integer object number from 0 to (classes-1)
> <x_center> <y_center> <width> <height> - float values relative to width and height of image, it can be equal from (0.0 to 1.0]
> for example: <x> = <absolute_x> / <image_width> or <height> = <absolute_height> / <image_height>
> atention: <x_center> <y_center> - are center of rectangle (are not top-left corner)
> For example for img1.jpg you will be created img1.txt containing:
> 
> 1 0.716797 0.395833 0.216406 0.147222
> 0 0.687109 0.379167 0.255469 0.158333
> 1 0.420312 0.395833 0.140625 0.166667

Since the "<x_center> <y_center> <width> <height>" values are already normalized to image widths and heights, you probably don't need to modify them when you change yolo model input dims.

I did create different txt files for different yolo input dims, because I wanted to filter out small objects relative to the input dim.

**Comment by Venketaramana** [comment]
Alright. Thank You. I will look into it.
